# EDA Y LIMPIEZA DE DATOS

## Presentación de los datos:

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

columnas = ['YY', 'MM','DD','hh','mm','WDIR','WSPD','GST','WVHT','DPD','APD','MWD','PRES','ATMP','WTMP','DEWP','VIS','PTDY','TIDE']

df23 = pd.read_fwf('NDBC_Caribe_2023.txt', skiprows=2, names=columnas)
df24 = pd.read_fwf('NDBC_Caribe_2024.txt', skiprows=2, names=columnas)
df25 = pd.read_fwf('NDBC_Caribe_2025.txt', skiprows=2, names=columnas)
df2601 = pd.read_fwf('NDBC_Caribe_2026-01.txt', skiprows=2, names=columnas)
df2604 = pd.read_fwf('NDBC_Caribe_2026-04.txt', skiprows=2, names=columnas)
df2605 = pd.read_fwf('NDBC_Caribe_2026-05.txt', skiprows=2, names=columnas)





df23

,YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,PTDY,TIDE
0,2023,4,13,20,10,75,8.6,10.8,1.88,7.14,5.13,112,1009.5,27.0,999.0,24.8,99.0,99.0,NaN
1,2023,4,13,20,20,78,8.2,10.0,99.00,99.00,99.00,999,1009.6,27.0,27.1,24.9,99.0,99.0,NaN
2,2023,4,13,20,30,78,8.6,10.5,99.00,99.00,99.00,999,1009.6,27.0,27.1,24.8,99.0,99.0,NaN
3,2023,4,13,20,40,77,8.5,10.1,1.74,7.14,5.03,110,1009.6,27.0,27.1,24.8,99.0,99.0,NaN
4,2023,4,13,20,50,77,8.6,10.2,99.00,99.00,99.00,999,1009.4,27.0,27.1,24.7,99.0,99.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37707,2023,12,31,23,10,67,7.8,9.4,1.81,9.09,5.64,359,1014.4,27.8,28.4,25.4,99.0,99.0,NaN
37708,2023,12,31,23,20,60,7.6,9.4,99.00,99.00,99.00,999,1014.5,27.8,28.4,25.5,99.0,99.0,NaN
37709,2023,12,31,23,30,60,8.0,9.8,99.00,99.00,99.00,999,1014.6,27.7,28.4,25.4,99.0,99.0,NaN
37710,2023,12,31,23,40,62,7.8,9.8,1.87,8.33,5.72,358,1014.6,27.7,28.4,25.4,99.0,99.0,NaN
37711,2023,12,31,23,50,64,7.8,9.8,99.00,99.00,99.00,999,1014.7,27.7,28.4,25.4,99.0,99.0,NaN

### Reordenamiento cronologico y detección de valores nulos

In [2]:
def EDA_clean_sort(df):

    filas_iniciales = len(df)

    #Reescribir la fecha como datetime

    df['Date'] = pd.to_datetime(
        df[['YY','MM','DD','hh','mm']]
        .rename(columns={
            'YY':'year',
            'MM':'month',
            'DD':'day',
            'hh':'hour',
            'mm':'minute'
        })
    )

    df = df[['Date','WDIR','WSPD','GST','WVHT','DPD','APD','MWD','PRES','ATMP','WTMP','DEWP','VIS','PTDY','TIDE']]
    
    #Volver los valores en NaN y eliminar columnas completamente vacias

    df = df.replace([99,999,9999], np.nan)
    df = df.dropna(axis=1, how='all')

    #Ordenar por datetime
    df = df.sort_values(['Date']).reset_index(drop=True)

    #Eliminar filas con valores NaN(Los reportes son cada 30 min)

    df = df.dropna().reset_index(drop=True)

    filas_finales = len(df)

    print("Resultados: " )
    print(f"Filas eliminadas: {filas_iniciales - filas_finales}")
    print(f"Filas restantes: {filas_finales}\n")

    return df

In [3]:
df23 = EDA_clean_sort(df23)
df24 = EDA_clean_sort(df24)
df25 = EDA_clean_sort(df25)
df2601 = EDA_clean_sort(df2601)
df2604 = EDA_clean_sort(df2604)
df2605 = EDA_clean_sort(df2605)

df23

Resultados:
Filas eliminadas: 25785
Filas restantes: 11927

Resultados:
Filas eliminadas: 34806
Filas restantes: 16243

Resultados:
Filas eliminadas: 35660
Filas restantes: 16858

Resultados:
Filas eliminadas: 2908
Filas restantes: 1352

Resultados:
Filas eliminadas: 3038
Filas restantes: 597

Resultados:
Filas eliminadas: 3203
Filas restantes: 1260

,Date,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP
0,2023-04-13 20:40:00,77.0,8.5,10.1,1.74,7.14,5.03,110.0,1009.6,27.0,27.1,24.8
1,2023-04-13 21:10:00,76.0,7.9,9.3,1.80,7.14,5.15,118.0,1009.8,27.0,27.1,24.8
2,2023-04-13 21:40:00,78.0,7.5,9.0,1.96,7.14,5.25,110.0,1009.9,27.1,27.1,24.9
3,2023-04-13 22:10:00,67.0,7.7,9.4,1.71,7.14,5.00,112.0,1010.1,27.0,27.1,24.9
4,2023-04-13 22:40:00,73.0,8.2,9.5,1.78,7.14,5.07,110.0,1009.9,26.9,27.1,24.3
...,...,...,...,...,...,...,...,...,...,...,...,...
11922,2023-12-31 21:40:00,82.0,7.4,8.9,1.80,5.88,5.46,73.0,1013.9,28.1,28.4,25.4
11923,2023-12-31 22:10:00,77.0,8.2,10.1,1.83,8.33,5.62,357.0,1014.1,27.9,28.4,24.9
11924,2023-12-31 22:40:00,72.0,7.9,10.0,1.86,9.09,5.84,355.0,1014.1,28.0,28.4,25.3
11925,2023-12-31 23:10:00,67.0,7.8,9.4,1.81,9.09,5.64,359.0,1014.4,27.8,28.4,25.4
11926,2023-12-31 23:40:00,62.0,7.8,9.8,1.87,8.33,5.72,358.0,1014.6,27.7,28.4,25.4

In [ ]:
df_train = pd.concat([df23, df24, df25], ignore_index=True)
df_train

,Date,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP
0,2026-05-05 03:40:00,71.0,10.4,12.1,1.86,7.14,5.08,97.0,1012.0,27.7,28.1,23.6
1,2026-05-05 04:10:00,71.0,10.1,12.0,1.86,7.69,4.87,93.0,1011.9,27.7,28.1,24.0
2,2026-05-05 04:40:00,74.0,10.1,12.0,1.82,7.69,4.99,101.0,1011.4,27.8,28.1,23.7
3,2026-05-05 05:40:00,77.0,9.4,11.5,1.86,7.69,5.06,100.0,1010.7,27.6,28.1,24.5
4,2026-05-05 06:10:00,82.0,9.5,11.0,1.87,7.69,5.15,101.0,1010.4,27.5,28.1,24.6
...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2026-05-31 21:10:00,67.0,8.8,11.3,2.19,7.69,5.74,96.0,1009.9,28.0,28.2,25.8
1256,2026-05-31 21:40:00,65.0,9.3,11.6,2.20,7.69,5.63,90.0,1009.9,28.0,28.1,25.7
1257,2026-05-31 22:10:00,65.0,9.3,11.2,2.17,7.69,5.46,91.0,1009.9,27.9,28.1,25.7
1258,2026-05-31 23:10:00,66.0,9.1,10.8,2.19,7.69,5.69,92.0,1010.4,27.9,28.1,25.8
1259,2026-05-31 23:40:00,70.0,8.7,11.0,2.16,7.69,5.60,93.0,1010.8,28.0,28.1,26.0

###