In [1]:
print("este es mi primer paper replicado (ojalá sea el último)")

este es mi primer paper replicado (ojalá sea el último)

In [1]:
import pandas as pd
import numpy as np

columnas = ['YY', 'MM', 'DD', 'hh', 'mm', 'WDIR', 'WSPD', 'GST', 'WVHT',
            'DPD', 'APD', 'MWD', 'PRES', 'ATMP', 'WTMP', 'DEWP', 'VIS', 'TIDE']

df = pd.read_fwf('datos_historicos_2023', skiprows=2, names=columnas)
df.replace([99.0, 99.00, 999, 999.0], np.nan, inplace=True)
df.head()

,YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2023,1,1,0,0,76.0,7.0,8.9,NaN,NaN,NaN,NaN,1023.3,23.1,24.4,18.6,NaN,NaN
1,2023,1,1,0,10,82.0,6.8,9.7,1.93,9.09,5.88,111.0,1023.4,23.1,24.4,18.9,NaN,NaN
2,2023,1,1,0,20,75.0,6.6,8.2,NaN,NaN,NaN,NaN,1023.4,23.1,24.5,18.9,NaN,NaN
3,2023,1,1,0,30,77.0,7.0,8.6,NaN,NaN,NaN,NaN,1023.5,23.1,24.5,18.9,NaN,NaN
4,2023,1,1,0,40,80.0,6.9,8.9,1.85,6.67,5.94,76.0,1023.5,23.1,24.4,19.0,NaN,NaN

In [2]:
df = df[['YY', 'MM', 'DD', 'hh', 'mm', 'WVHT', 'WSPD', 'WTMP']]

df['datetime'] = pd.to_datetime(
    df[['YY', 'MM', 'DD', 'hh', 'mm']].rename(columns={
        'YY': 'year',
        'MM': 'month',
        'DD': 'day',
        'hh': 'hour',
        'mm': 'minute' 
    })
)

df = df.rename(columns={
    'WVHT': 'Hs',
    'WSPD': 'Wind_speed',
    'WTMP': 'sst'
})

df = df[['datetime', 'Hs', 'Wind_speed', 'sst']]

df.head()

             datetime    Hs  Wind_speed   sst
0 2023-01-01 00:00:00   NaN         7.0  24.4
1 2023-01-01 00:10:00  1.93         6.8  24.4
2 2023-01-01 00:20:00   NaN         6.6  24.5
3 2023-01-01 00:30:00   NaN         7.0  24.5
4 2023-01-01 00:40:00  1.85         6.9  24.4

In [3]:
from statsmodels.tsa.stattools import adfuller

variables = ['Wind_speed', 'sst', 'Hs']

for var in variables:
    
    # Eliminar NaN
    serie = df[var].dropna()
    
    # Aplicar ADF test
    resultado = adfuller(serie)
    
    print(f'\nADF Test para {var}')
    print(f'ADF Statistic: {resultado[0]}')
    print(f'p-value: {resultado[1]}')
    
    if resultado[1] < 0.05:
        print('La serie es estacionaria')
    else:
        print('La serie NO es estacionaria')

ADF Test para Wind_speed
ADF Statistic: -15.07787927923801
p-value: 8.53829131599943e-28
La serie es estacionaria

ADF Test para sst
ADF Statistic: -1.4033483424383648
p-value: 0.580669832503169
La serie NO es estacionaria

ADF Test para Hs
ADF Statistic: -6.657317308515785
p-value: 4.9466378794320084e-09
La serie es estacionaria